#!/bin/bash
# DRIP Node Setup Script for Linux
# This script sets up Tor and configures DRIP for running with onion support
# Run this after building DRIP on a new machine
#
# BUILD INSTRUCTIONS (run before this script):
# --------------------------------------------
# Ubuntu/Debian:
#   sudo apt-get install build-essential cmake pkgconf python3 \
#       libevent-dev libboost-dev libsqlite3-dev
#
#   git clone https://github.com/Digital-Reserve/DRIP.git
#   cd DRIP
#   cmake -B build -DENABLE_IPC=OFF
#   cmake --build build -j$(nproc)
#
# Then run: ./contrib/setup-drip-node.sh
# --------------------------------------------

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

echo -e "${CYAN}========================================${NC}"
echo -e "${CYAN}  DRIP Node Setup Script (Linux)${NC}"
echo -e "${CYAN}========================================${NC}"
echo ""

# Paths
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DRIP_ROOT="$(dirname "$SCRIPT_DIR")"
DRIP_DATA_DIR="$HOME/.drip"

echo -e "DRIP Root: ${YELLOW}$DRIP_ROOT${NC}"
echo -e "DRIP Data Directory: ${YELLOW}$DRIP_DATA_DIR${NC}"
echo ""

# ============================================
# Step 1: Install Tor via package manager
# ============================================
echo -e "${YELLOW}[1/4] Installing Tor...${NC}"

if command -v tor &> /dev/null; then
    echo -e "  ${GREEN}Tor already installed${NC}"
else
    if command -v apt &> /dev/null; then
        echo "  Installing via apt..."
        sudo apt update
        sudo apt install -y tor
    elif command -v dnf &> /dev/null; then
        echo "  Installing via dnf..."
        sudo dnf install -y tor
    elif command -v pacman &> /dev/null; then
        echo "  Installing via pacman..."
        sudo pacman -S --noconfirm tor
    else
        echo -e "  ${RED}Could not detect package manager. Please install Tor manually.${NC}"
        exit 1
    fi
    echo -e "  ${GREEN}Done!${NC}"
fi

# ============================================
# Step 2: Configure Tor
# ============================================
echo -e "${YELLOW}[2/4] Configuring Tor...${NC}"

# Check if we need to modify torrc
TORRC="/etc/tor/torrc"
if grep -q "^ControlPort 9051" "$TORRC" 2>/dev/null; then
    echo -e "  ${GREEN}Tor already configured with ControlPort${NC}"
else
    echo "  Adding ControlPort configuration to $TORRC..."
    sudo tee -a "$TORRC" > /dev/null << 'EOF'

# DRIP Node Configuration
ControlPort 9051
CookieAuthentication 1
CookieAuthFileGroupReadable 1
DataDirectoryGroupReadable 1
EOF
    echo -e "  ${GREEN}Done!${NC}"
    
    # Add user to tor group for cookie access
    echo "  Adding $USER to debian-tor group..."
    sudo usermod -a -G debian-tor "$USER" 2>/dev/null || sudo usermod -a -G tor "$USER" 2>/dev/null || true
    echo -e "  ${YELLOW}NOTE: You may need to log out and back in for group changes to take effect${NC}"
fi

# Restart Tor
echo "  Restarting Tor service..."
sudo systemctl restart tor
sudo systemctl enable tor
echo -e "  ${GREEN}Done!${NC}"

# ============================================
# Step 3: Create DRIP Data Directory & Config
# ============================================
echo -e "${YELLOW}[3/4] Creating DRIP configuration...${NC}"

mkdir -p "$DRIP_DATA_DIR"

cat > "$DRIP_DATA_DIR/bitcoin.conf" << 'EOF'
# DRIP Node Configuration
# Auto-generated by setup-drip-node.sh
# Using -drip chain type (default)

# ===============
# Network Settings
# ===============
listen=1

# Enable debug logging for Tor and network
debug=tor
debug=net

# ===============
# Tor Settings
# ===============
# Use Tor proxy for all outgoing connections
proxy=127.0.0.1:9050

# Enable automatic onion service creation
listenonion=1

# Tor control port for automatic onion address generation
torcontrol=127.0.0.1:9051

# ===============
# RPC Settings (for drip-cli)
# ===============
server=1

# ===============
# Add peers here as you find them
# ===============
# addnode=PEER_ONION_ADDRESS.onion:58333
EOF

echo -e "  Created: ${GREEN}$DRIP_DATA_DIR/bitcoin.conf${NC}"

# ============================================
# Step 4: Verify Installation
# ============================================
echo -e "${YELLOW}[4/4] Verifying installation...${NC}"

ALL_GOOD=true

if command -v tor &> /dev/null; then
    echo -e "  ${GREEN}[OK]${NC} Tor installed"
else
    echo -e "  ${RED}[MISSING]${NC} Tor not installed"
    ALL_GOOD=false
fi

if systemctl is-active --quiet tor; then
    echo -e "  ${GREEN}[OK]${NC} Tor service running"
else
    echo -e "  ${RED}[NOT RUNNING]${NC} Tor service not running"
    ALL_GOOD=false
fi

if [ -f "$DRIP_DATA_DIR/bitcoin.conf" ]; then
    echo -e "  ${GREEN}[OK]${NC} DRIP config created"
else
    echo -e "  ${RED}[MISSING]${NC} DRIP config not found"
    ALL_GOOD=false
fi

if [ -f "$DRIP_ROOT/build/bin/dripd" ]; then
    echo -e "  ${GREEN}[OK]${NC} DRIP daemon found"
else
    echo -e "  ${YELLOW}[MISSING]${NC} DRIP daemon not found - did you build the project?"
    ALL_GOOD=false
fi

echo ""
echo -e "${CYAN}========================================${NC}"

if $ALL_GOOD; then
    echo -e "  ${GREEN}Setup Complete!${NC}"
    echo -e "${CYAN}========================================${NC}"
    echo ""
    echo -e "To start the DRIP node:"
    echo ""
    echo -e "  ${YELLOW}$DRIP_ROOT/build/bin/dripd -drip -printtoconsole${NC}"
    echo ""
    echo -e "To get your onion address:"
    echo ""
    echo -e "  ${YELLOW}$DRIP_ROOT/build/bin/drip-cli -drip getnetworkinfo${NC}"
    echo ""
    echo -e "${YELLOW}NOTE: If you just added yourself to the tor group, log out and back in first!${NC}"
else
    echo -e "  ${RED}Setup Incomplete - See errors above${NC}"
    echo -e "${CYAN}========================================${NC}"
fi

