# DRIP Node Setup Script
# This script sets up Tor and configures DRIP for running with onion support
# Run this after building DRIP on a new machine

param(
    [switch]$SkipTorDownload,
    [switch]$StartServices
)

$ErrorActionPreference = "Stop"

Write-Host "========================================" -ForegroundColor Cyan
Write-Host "  DRIP Node Setup Script" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""

# Paths
$DripRoot = Split-Path -Parent (Split-Path -Parent $PSScriptRoot)
if (-not (Test-Path "$DripRoot\build\bin\dripd.exe")) {
    $DripRoot = "C:\drip"
}
$TorDir = "$DripRoot\tor"
$TorDataDir = "$TorDir\data"
$DripDataDir = "$env:LOCALAPPDATA\DRIP"

Write-Host "DRIP Root: $DripRoot" -ForegroundColor Gray
Write-Host "Tor Directory: $TorDir" -ForegroundColor Gray
Write-Host "DRIP Data Directory: $DripDataDir" -ForegroundColor Gray
Write-Host ""

# ============================================
# Step 1: Create Directories
# ============================================
Write-Host "[1/5] Creating directories..." -ForegroundColor Yellow

New-Item -ItemType Directory -Path $TorDir -Force | Out-Null
New-Item -ItemType Directory -Path $TorDataDir -Force | Out-Null
New-Item -ItemType Directory -Path $DripDataDir -Force | Out-Null

Write-Host "  Done!" -ForegroundColor Green

# ============================================
# Step 2: Download Tor Expert Bundle
# ============================================
if (-not $SkipTorDownload) {
    Write-Host "[2/5] Downloading Tor Expert Bundle..." -ForegroundColor Yellow
    
    $TorUrl = "https://archive.torproject.org/tor-package-archive/torbrowser/14.0.4/tor-expert-bundle-windows-x86_64-14.0.4.tar.gz"
    $TorArchive = "$TorDir\tor-expert-bundle.tar.gz"
    
    if (Test-Path "$TorDir\tor\tor.exe") {
        Write-Host "  Tor already exists, skipping download." -ForegroundColor Gray
    } else {
        Write-Host "  Downloading from torproject.org..." -ForegroundColor Gray
        Invoke-WebRequest -Uri $TorUrl -OutFile $TorArchive -UseBasicParsing
        
        Write-Host "  Extracting..." -ForegroundColor Gray
        Push-Location $TorDir
        tar -xzf tor-expert-bundle.tar.gz
        Pop-Location
        
        Write-Host "  Done!" -ForegroundColor Green
    }
} else {
    Write-Host "[2/5] Skipping Tor download (flag set)" -ForegroundColor Gray
}

# ============================================
# Step 3: Create Tor Configuration
# ============================================
Write-Host "[3/5] Creating Tor configuration..." -ForegroundColor Yellow

$TorConfig = @"
# Tor configuration for DRIP node
# Auto-generated by setup-drip-node.ps1

# SOCKS port for proxy connections
SocksPort 127.0.0.1:9050

# Control port for DRIP to create onion services
ControlPort 127.0.0.1:9051

# Cookie authentication
CookieAuthentication 1
CookieAuthFile $TorDataDir\control_auth_cookie

# Data directory
DataDirectory $TorDataDir

# GeoIP files
GeoIPFile $TorDataDir\geoip
GeoIPv6File $TorDataDir\geoip6

# Logging
Log notice file $TorDataDir\tor.log
"@

$TorConfig | Out-File -FilePath "$TorDataDir\torrc" -Encoding ASCII
Write-Host "  Created: $TorDataDir\torrc" -ForegroundColor Green

# ============================================
# Step 4: Create DRIP Configuration
# ============================================
Write-Host "[4/5] Creating DRIP configuration..." -ForegroundColor Yellow

$DripConfig = @"
# DRIP Node Configuration
# Auto-generated by setup-drip-node.ps1

[drip]
# Network Settings
listen=1
debug=tor

# Tor Settings
proxy=127.0.0.1:9050
listenonion=1
torcontrol=127.0.0.1:9051

# RPC Settings
server=1

# Add peers here
# addnode=PEER_ONION_ADDRESS.onion:58333
"@

$DripConfig | Out-File -FilePath "$DripDataDir\bitcoin.conf" -Encoding ASCII
Write-Host "  Created: $DripDataDir\bitcoin.conf" -ForegroundColor Green

# ============================================
# Step 5: Verify Installation
# ============================================
Write-Host "[5/5] Verifying installation..." -ForegroundColor Yellow

$AllGood = $true

if (Test-Path "$TorDir\tor\tor.exe") {
    Write-Host "  [OK] Tor executable found" -ForegroundColor Green
} else {
    Write-Host "  [MISSING] Tor executable not found at $TorDir\tor\tor.exe" -ForegroundColor Red
    $AllGood = $false
}

if (Test-Path "$TorDataDir\torrc") {
    Write-Host "  [OK] Tor config created" -ForegroundColor Green
} else {
    Write-Host "  [MISSING] Tor config not found" -ForegroundColor Red
    $AllGood = $false
}

if (Test-Path "$DripDataDir\bitcoin.conf") {
    Write-Host "  [OK] DRIP config created" -ForegroundColor Green
} else {
    Write-Host "  [MISSING] DRIP config not found" -ForegroundColor Red
    $AllGood = $false
}

if (Test-Path "$DripRoot\build\bin\dripd.exe") {
    Write-Host "  [OK] DRIP daemon found" -ForegroundColor Green
} else {
    Write-Host "  [MISSING] DRIP daemon not found - did you build the project?" -ForegroundColor Red
    $AllGood = $false
}

Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan

if ($AllGood) {
    Write-Host "  Setup Complete!" -ForegroundColor Green
    Write-Host "========================================" -ForegroundColor Cyan
    Write-Host ""
    Write-Host "To start the DRIP node with Tor:" -ForegroundColor White
    Write-Host ""
    Write-Host "  # Terminal 1 - Start Tor first:" -ForegroundColor Gray
    Write-Host "  $TorDir\tor\tor.exe -f $TorDataDir\torrc" -ForegroundColor Yellow
    Write-Host ""
    Write-Host "  # Terminal 2 - Wait for Tor to reach 100%, then start DRIP:" -ForegroundColor Gray
    Write-Host "  $DripRoot\build\bin\dripd.exe -drip -printtoconsole" -ForegroundColor Yellow
    Write-Host ""
    Write-Host "  # To get your onion address:" -ForegroundColor Gray
    Write-Host "  $DripRoot\build\bin\drip-cli.exe -drip getnetworkinfo" -ForegroundColor Yellow
    Write-Host ""
    
    if ($StartServices) {
        Write-Host "Starting services..." -ForegroundColor Yellow
        Write-Host ""
        
        # Start Tor in new window
        Start-Process cmd -ArgumentList "/k", "title TOR && `"$TorDir\tor\tor.exe`" -f `"$TorDataDir\torrc`""
        
        Write-Host "Waiting for Tor to bootstrap..." -ForegroundColor Gray
        Start-Sleep -Seconds 8
        
        # Start DRIP in new window
        Start-Process cmd -ArgumentList "/k", "title DRIP-NODE && `"$DripRoot\build\bin\dripd.exe`" -drip -printtoconsole"
        
        Write-Host "Services started in separate windows!" -ForegroundColor Green
    }
} else {
    Write-Host "  Setup Incomplete - See errors above" -ForegroundColor Red
    Write-Host "========================================" -ForegroundColor Cyan
}

